### PR TITLE
First step to show infovis layers in layer-browser

### LINKED ISSUE #998: Add a general non-geospatial layer-browser
We need an example similar to layer-browser for non-geospatial layers so that they won't be accidentally broken.

### PR DESCRIPTION
**Pull request by ibgreen**
Lots of limitations but at least can now test that plot layer is rendering.

Partially fixes #998 

screen shot 2017-12-02 at 8 12 06 am

### CODE REVIEW

**Comment by ibgreen** [comment]
@shaojingli Per feedback, added label to show that Navigation is not available

screen shot 2017-12-04 at 12 58 31 pm

File: examples/layer-browser/src/app.js [hunk 1]
```diff
@@ -68,22 +70,30 @@ class App extends PureComponent {
...
-        separation: 0
-        // the rotation controls works only for layers in
-        // meter offset projection mode. They are commented out
-        // here since layer browser currently only have one layer
-        // in this mode, and that layer's data is rotation symmetrical
-        // rotationZ: 0,
-        // rotationX: 0
+        // Model matrix manipulation
+        separation: 0,
+        rotationZ: 0,
```
Comment (jianhuang01) [inline examples/layer-browser/src/app.js]: rotationY ? cause the orbitAxis is 'Y'

File: examples/layer-browser/src/app.js [hunk 2]
```diff
@@ -197,38 +207,46 @@ class App extends PureComponent {
...
-  }
-
   _getViewports() {
-    const {width, height, mapViewState, settings: {multiview}} = this.state;
+    const {
+      width, height, mapViewState, orbitViewState,
+      settings: {infovis, multiview}
+    } = this.state;
+
+    if (infovis) {
```
Comment (jianhuang01) [inline examples/layer-browser/src/app.js]: Use infovis to switch between geospatial vs non-geospatial examples everywhere, not very scalable for new non-geospatial example in the future.

File: examples/layer-browser/src/app.js (hunk 1 above)
Comment (ibgreen) [reply examples/layer-browser/src/app.js]: > rotationY ? cause the orbitAxis is 'Y'

Ah... that control is for geospatial layers. Will consider how to make it work for infovis.

File: examples/layer-browser/src/app.js (hunk 2 above)
Comment (ibgreen) [reply examples/layer-browser/src/app.js]: > 

For sure this was just intended to get us started.

FWIW, there is a `layerFilter` function which automatically shows all `COORDINATE_SYSTEM.IDENTITY` when in infovis mode. No need to add more if statements to each example, so should be somewhat "scalable" in that sense.

Although there are probably an issue if the demo layers use data sets with very different extents, we may want to scale them to similar size (maybe using modelMatrix).

I also thought about putting two viewports on top of each other so that all layers are visible. We can refine it like that later on.

File: examples/layer-browser/src/app.js [hunk 3]
```diff
@@ -197,38 +207,46 @@ class App extends PureComponent {
...
 
-  _renderNoTokenWarning() {
-    /* eslint-disable max-len */
-    return (
-      <div id="no-token-warning">
-        <h3>No Mapbox access token found.</h3>
-        Read <a href="http://uber.github.io/deck.gl/#/documentation/overview/getting-started#note-on-map-tokens-">"Note on Map Tokens"</a> for information on setting up your basemap.
-      </div>
-    );
-    /* eslint-disable max-len */
```
Comment (jianhuang01) [inline examples/layer-browser/src/app.js]: why remove token warning message? we need it for geospatial examples.

File: examples/layer-browser/src/app.js (hunk 1 above)
Comment (ibgreen) [reply examples/layer-browser/src/app.js]: > rotationY ? cause the orbitAxis is 'Y'

Support for rotating infovis layers using model matrix is a relatively minor feature. Would be a different PR.

File: examples/layer-browser/src/app.js (hunk 3 above)
Comment (ibgreen) [reply examples/layer-browser/src/app.js]: > why remove token warning message? we need it for geospatial examples.

The good news is that react-map-gl 3.1 now handles token warning, no need to do it in each example.
