### PR TITLE
Make sure picking blend modes override layer `parameters` during picking

### LINKED ISSUE #878: layer 'blend' parameters override picking settings, causing crash
Easily seen below, `layer.parameters are passed` in to `drawLayer` at the end.
```
return withParameters(gl, {
    framebuffer: pickingFBO,
    scissorTest: true,
    scissor: [x, y, width, height],
    blend: true,
    blendFunc: [gl.ONE, gl.ZERO, gl.CONSTANT_ALPHA, gl.ZERO],
    blendEquation: gl.FUNC_ADD,
    clearColor: [0, 0, 0, 0]
  }, () => {

    // Clear the frame buffer
    gl.clear(GL.COLOR_BUFFER_BIT | GL.DEPTH_BUFFER_BIT);

    // Render all pickable layers in picking colors
    layers.forEach((layer, layerIndex) => {
      if (!layer.isComposite && layer.props.visible && layer.props.pickable) {

        // Encode layerIndex with alpha
        setParameters(gl, {blendColor: [0, 0, 0, (layerIndex + 1) / 255]});
        layer.drawLayer({
          moduleParameters: Object.assign({}, layer.props, {
            viewport: layer.context.viewport
          }),
          uniforms: Object.assign(
            // TODO: Update all layers to use 'picking_uActive' (picking shader module)
            // and then remove 'renderPickingBuffer' and 'pickingEnabled'.
            {
              renderPickingBuffer: 1,
              pickingEnabled: 1,
              picking_uActive: 1
            },
            layer.context.uniforms,
            {layerIndex}
          ),
          parameters: layer.props.parameters || {}
        });
      }
```

### PR DESCRIPTION
**Pull request by ibgreen**
Fixes #878

### CODE REVIEW

File: src/lib/draw-and-pick.js [hunk 1]
```diff
@@ -390,7 +386,13 @@ function getPickedColors(gl, {
...
             {layerIndex}
           ),
-          parameters: layer.props.parameters || {}
+          // Blend parameters must not be overriden
+          parameters: Object.assign({}, layer.props.parameters || {}, {
+            blend: true,
+            blendFunc: [gl.ONE, gl.ZERO, gl.CONSTANT_ALPHA, gl.ZERO],
+            blendEquation: gl.FUNC_ADD,
+            clearColor: [0, 0, 0, 0]
+          })
```
Comment (shaojingli) [inline src/lib/draw-and-pick.js]: Very good catch...
