### PR TITLE
WindDemo: Rename uniforms

### LINKED ISSUE #1286: Wind demo regressions
- [ ] Shaders using deprecated/removed uniforms like 'projectionMode', if no custom lighting/projections used , removed this shader code and use `porject` and `lighting` modules.
- [ ] Lighting of elevation layer looks in-correct.

### PR DESCRIPTION
**Pull request by 1chandu**
- Fixes #1286 
- Create fragment shader versions of `fp32`, `project` and `lighting` shader modules.
- Remove duplicated shader code from `delaunay-cover` and `wind` layer and use above shader modules.

Verified running wind demo.

### CODE REVIEW

**Comment by 1chandu** [comment]
@ibgreen , its doing per-fragment lighting, so needed project methods in fragment shader. When we support per-fragment lighting in `lighting` shader module this can be simplified.

File: examples/wind/src/shaderlib/fs-fp32/fs-fp32.js [hunk 1]
```diff
@@ -0,0 +1,159 @@
+// NOTE: this is same as luma.gl 'fp32' module except this is applied to fragment shader.
+const fsfp32shader = `\
```
Comment (ibgreen) [inline examples/wind/src/shaderlib/fs-fp32/fs-fp32.js]: Maybe no need to copy the text? Can't we just import the luma.gl module and just create a new javascript object 
`export default {fs: vsmodule.vs}`
?
