### PR TITLE
Fix picking

### LINKED ISSUE #73: click events not working?
index always comes back as -1 after updating to the latest (2.4.8)

### PR DESCRIPTION
**Pull request by ibgreen**
Fixes #73

@gnavvy @abmai @contra

Using the new luma logging it was easy to spot that the picking colors attribute was all zeroes. Fixed by a one line change to second parameter in `Layer.calculateInstancePickingColors`.

### CODE REVIEW

File: src/layers/base-layer.js [hunk 1]
```diff
@@ -396,7 +396,7 @@ export default class BaseLayer {
     this.willUnmount();
   }
 
-  calculateInstancePickingColors(attribute, numInstances) {
+  calculateInstancePickingColors(attribute, {numInstances}) {
```
Comment (gnavvy) [inline src/layers/base-layer.js]: could you add jsdoc to this function on what is the second param and why we need to unpack numInstances out of it?
