### PR TITLE
Fix crash during pickVisibleObjects

### LINKED ISSUE #1344: `pickObjects` throws assertion error due to NaNs for ScatterplotLayer
Within `pickVisibleObjects`, `getUniquesFromPickingBuffer` is creating an Array of `pickInfos`. None of these have an `x` or `y` value (they only have `pickedColor`, `pickedLayer`, and `pickedObjectIndex`). Because of this, the first Array arg passed to `createInfo` has `NaN`s, which throws inside of `pixelsToWorld` when it asserts that the Array values are finite numbers.

Note that `pickObject` (singular) works fine with the exact same arguments.

### PR DESCRIPTION
**Pull request by 1chandu**
Closes #1344

`pickVisibleObjects` should bounding box (x, y, width and height in pixels) in result , as described in docs.

Verified with layer-browser.

### CODE REVIEW

File: src/core/lib/pick-layers.js [hunk 1]
```diff
@@ -150,13 +150,17 @@ export function pickVisibleObjects(
   const uniqueInfos = new Map();
 
   pickInfos.forEach(pickInfo => {
-    const viewport = getViewportFromCoordinates({viewports}); // TODO - add coords
-    let info = createInfo([pickInfo.x / pixelRatio, pickInfo.y / pixelRatio], viewport);
```
Comment (ibgreen) [inline src/core/lib/pick-layers.js]: What happens to the `createInfo` function? Should it be deleted now? Or is it used somewhere else?

Comment (1chandu) [reply src/core/lib/pick-layers.js]: It is still used in during `pickObjets` , only thing that is done there is to unproject the (x,y) to LatLng, if preferred I can remove that function and inline the code.

Comment (ibgreen) [reply src/core/lib/pick-layers.js]: Yes I think we should align the code paths.
