### PR TITLE
Fix Layer#checkProp to only error on undefined/null

### LINKED ISSUE #31: (dev branch) Layer prop validation fails on valid 0 values
The `Layer` class validates input with `if (!property)`. This fails on `0` values for zoom, latitude, and longitude.

### PR DESCRIPTION
**Pull request by austinhyde**
Fixes #31 

I added unit tests confirming this behavior, but there's still a test failure on

```
⨯ Viewport projection matrix
  not ok 7 TypeError: viewport.getZoomedViewProjectionMatrix is not a function
    ---
      operator: error
      expected: 
      actual:   {}
      at: Test.exports.Test.run (/Users/Hyde/src/deck.gl/node_modules/tape-catch/index.js:29:10)
      stack:
        TypeError: viewport.getZoomedViewProjectionMatrix is not a function
          at Test._cb (viewport-spec.js:55:39)
```

I'm not sure the best solution to this, so I just left it as-is.

### CODE REVIEW

File: test/layer-spec.js [hunk 1]
```diff
@@ -16,13 +16,45 @@ const LAYER_PROPS = {
...
   t.end();
 });
 
+test('Layer#constructor with zeroes', t => {
+  const layer = new Layer(LAYER_PROPS_ZEROES);
+  t.ok(layer, 'Layer created');
+  t.end();
+});
+
+test('Layer#constructor with missing prps', t => {
```
Comment (ibgreen) [inline test/layer-spec.js]: `prps` => `props`

File: src/layer.js [hunk 2]
```diff
@@ -455,8 +456,8 @@ export default class Layer {
   }
 
   checkProp(property, propertyName) {
-    if (!property) {
-      throw new Error(`Property ${propertyName} undefined in layer ${this.id}`);
+    if (typeof property === 'undefined' || property === null) {
```
Comment (ibgreen) [inline src/layer.js]: Should be enough to do
```if (property === undefined || property === null)```

**Comment by ibgreen** [comment]
@austinhyde 
Looks great
Love the fact that you added unit tests! 
I think the breaking function has just changed name to `getProjectionMatrix()`. You can make the change, or leave it and I'll fix it later.
I added some inline nits, but they are not blockers, I am fine to merge this as is. 
Let's chat offline if you need a new version published.

**Comment by austinhyde** [comment]
I wasn't able to fix the projection matrix test - the expected data doesn't line up with the results from `getProjectionMatrix()`:

```javascript
// actual
[
  7.816546440124512, -5.682946681976318, -1.9806208610534668, -1.808401107788086,
  -7.678424835205078, -5.785172939300537, -2.0162487030029297, -1.8409311771392822,
  0, 7.7417097091674805, -2.9606006145477295, -2.703169345855713,
  879.8411865234375, 1610.45068359375, 562.7077026367188, 513.97021484375
]
// expected
[
  0.0026987954042851925, -0.001962133916094899, -0.0006838429835624993, -0.0006243811803869903,
  -0.0026511065661907196, -0.0019974291790276766, -0.0006961441249586642, -0.0006356127560138702,
  0, 0.0026729567907750607, -0.001022197655402124, -0.0009333151392638683,
  879.8411865234375, 1610.45068359375, 562.7077026367188, 513.97021484375
]
```

**Comment by ibgreen** [comment]
I see. Yes, the projection has changed scale, I'll handle that.
