### PR TITLE
Fix GPUGridLayer crash when used with GridLayer

### LINKED ISSUE #3525: GPUGridLayer crashes when used with GridLayer
#### Description

GPUGridLayer crashes when used with GridLayer
#### Repro Steps

1. In `examples/layer-browser` run `npm run start-local`
2. Deselect `ScatterplotLayer` so that we can see results clearly.
3. Select `GridLayer` and then select `GPUGridLayer` and now deselect `GridLayer`.  
The screen should display `GPUGridLayer` only but you'll see a blank screen.
4. Deselect  `GPUGridLayer` and it'll crash.

gpugridcrash

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.3.0-alpha.4]
 - Browser Version: [e.g. Chrome 76.0]
 - OS: [e.g. Ubuntu 18.04.3 LTS]

#### Logs

Screenshot from 2019-09-05 22-16-43

### PR DESCRIPTION
**Pull request by Navneet-Sahota**
close #3525

For #3525

#### Background
GPUGridLayer crashes when used with GridLayer as both the layers are given same id from `GRID_LAYER_PROPS` object.
#### Change List
- Made different objects to provide props with different id to each layer

### CODE REVIEW

**Comment by Navneet-Sahota** [comment]
@1chandu Kindly review these changes.

File: examples/layer-browser/src/examples/additional-layers.js [hunk 1]
```diff
@@ -17,16 +17,25 @@ import * as dataSamples from '../data-samples';
 
 registerLoaders([PLYLoader]);
 
+const gridLayerProps = {
```
Comment (1chandu) [inline examples/layer-browser/src/examples/additional-layers.js]: Use `GRID_LAYER_PROPS` and `GPU_GRID_LAYER_PROPS`, similar to line 41.

Comment (Navneet-Sahota) [reply examples/layer-browser/src/examples/additional-layers.js]: Changed names to `GRID_LAYER_PROPS_OBJECT` and `GPU_GRID_LAYER_PROPS_OBJECT` since `GRID_LAYER_PROPS` and `GPU_GRID_LAYER_PROPS` names were already in use.
