### PR TITLE
Example fixes.

### LINKED ISSUE #411: Polygon outline flicker in the GeoJSONLayer
The filled part and stroked outline of polygons in GeoJSONLayer flickers really bad due to z-fighting. It's a small issue technically, but visually very unpleasing.

mar-09-2017 11-19-01

### LINKED ISSUE #840: HexagonCellLayer documentation refers to a seemingly non-existent getRadius(d) method
The [coverage section](https://github.com/uber/deck.gl/blob/f132d93e01c497ccab79a7981de73a6a628ee509/docs/layers/hexagon-cell-layer.md#coverage-number-optional) of the `HexagonCellLayer` documentation states that
```
The radius of hexagon is calculated by `coverage * getRadius(d)`
```
but as best I can tell it's simply `coverage * radius`.

It'd be very nice to have a hexagon-specific radius so that you could have e.g. radius represent counts and color represent rates (for instance to not give too much visual weight to sparsely populated areas) like `ScatterplotLayer` provides. 

Is the documentation incorrect, is there work in that direction off on another branch, or am I just wrong and misreading things? Thanks!

### LINKED ISSUE #882: Example 'burshing` throws Illegal attribute generation error
Following warning is generated and rendering also looks incorrect, need to viery.

```
deck.gl deck.gl error during update of <ScatterplotBrushingLayer:'sources'> Error: Illegal attribute generated for instanceTargetPositions
    at AttributeManager._checkAttributeArray (attribute-manager.js:619)
    at AttributeManager._updateBuffer (attribute-manager.js:570)
    at AttributeManager._updateBuffers (attribute-manager.js:553)
    at AttributeManager.update (attribute-manager.js:262)
    at ScatterplotBrushingLayer.updateAttributes (layer.js:189)
    at ScatterplotBrushingLayer.updateLayer (layer.js:414)
    at LayerManager._updateLayer (layer-manager.js:514)
    at loop (layer-manager.js:381)
    at LayerManager._matchSublayers (layer-manager.js:425)
    at LayerManager._updateLayers (layer-manager.js:349)
```

### PR DESCRIPTION
**Pull request by 1chandu**
Brushing : data source only contains vec2, use '0' for z component. Fixes #882 
Layer-browser:GeoJson : enable fp64 by default to avoid z-fighting between layers. Fixes #411 
Minor documentation changes. Fixes #840

### CODE REVIEW

File: examples/brushing/deckgl-overlay.js [hunk 1]
```diff
@@ -160,7 +160,8 @@ export default class DeckGLOverlay extends Component {
         pickable: false,
         // only show source points when brushing
         radiusScale: startBrushing ? 3000 : 0,
-        getColor: d => (d.gain > 0 ? targetColor : sourceColor)
+        getColor: d => (d.gain > 0 ? targetColor : sourceColor),
+        getTargetPosition: d => [d[0], d[1], 0]
```
Comment (ibgreen) [inline examples/brushing/deckgl-overlay.js]: I think many layers check the last coordinate and set it to zero. But it is OK to fix it here.

File: docs/layers/hexagon-cell-layer.md [hunk 2]
```diff
@@ -67,7 +67,7 @@ they will be used to calculate primitive hexagon instead of `hexagonVertices`
 - Default: `1`
 
 Hexagon radius multiplier, between 0 - 1. The radius of hexagon is calculated by
-`coverage * getRadius(d)`
+`coverage * radius`
```
Comment (1chandu) [inline docs/layers/hexagon-cell-layer.md]: @ibgreen added this minor doc change as described in #840
