### PR TITLE
use offsetX & offsetY instead of x & y to get relative positions

### LINKED ISSUE #248: Mouse event positions incorrect when page scrolled
When the map is partially scrolled out of view, click events do not work as expected (see image). This issue only happens when the main page scroll is scrolling the map out of view, not the scroll of a containing element. From what I can tell, this is a bug in luma.gl. I will also file an issue there.

map bug

### PR DESCRIPTION
**Pull request by gnavvy**
fixes #248 and #444 
tested (ad-hoc) in the svg-interoperability example with a scolled offset.
will add a dedicated example consist of multiple non-full screen widgets later.

### CODE REVIEW

File: src/react/deckgl.js [hunk 1]
```diff
@@ -119,7 +119,7 @@ export default class DeckGL extends React.Component {
 
   // Route events to layers
   _onClick(event) {
-    const {x, y} = event;
+    const {event: {offsetX: x = 0, offsetY: y = 0} = {}} = event;
```
Comment (gnavvy) [inline src/react/deckgl.js]: Just a sanity check. 

I agree it makes more sense to drop the event if either `event.event` is falsy (luma.gl addEvent fails, shouldn't be) or `offsetX` `offsetY` are falsy (browser fails, again shouldn't be according to the [spec](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX)); it's also heavy and requires changes on existing apps if we surface the error message via the picked object.

will just drop the event if sanity check fails.
