### PR TITLE
Fix ColumnLayer elevationScale example

### LINKED ISSUE #3541: ColumnLayer elevationScale default max limit
#### Description

ColumnLayer's `elevationScale` in the documentation is set to `5000` initially, but the input range have a default max value of `100`, so it does not move beyond 100 once changed from the initial state.
#### Repro Steps

err

#### Environment (please complete the following information):
- Framework Version: [e.g. deck.gl 7.2.3]
 - Browser Version: [e.g. Chrome 76.0]
 - OS: [e.g. Ubuntu 18.04.3 LTS]

#### Logs

No warnings or error is thrown

### PR DESCRIPTION
**Pull request by Navneet-Sahota**
Fix #3541

#### Background
ColumnLayer's `elevationScale` in the documentation is set to `5000` initially, but the input range have a default max value of `100`, so it does not move beyond 100 once changed from the initial state.
Here, I pass a `max` prop to input field with value equal to `5000` .

sol

### CODE REVIEW

File: website/src/utils/layer-params.js [hunk 1]
```diff
@@ -56,7 +56,11 @@ export function getLayerParams(layer, propParameters = {}) {
     if (propParameters[key]) {
       paramsArray.push({name: key, ...propParameters[key]});
     } else {
-      const param = propToParam(key, layer.constructor._propTypes[key], layer.props[key]);
+      const LAYER_PROPTYPES = layer.constructor._propTypes[key];
+      if (layer.constructor.name === 'ColumnLayer') {
```
Comment (Pessimistress) [inline website/src/utils/layer-params.js]: I'm not a fan of special cases like this. Can we scale up the `getElevation` prop instead and keep the default range?

Comment (Navneet-Sahota) [reply website/src/utils/layer-params.js]: Yes, that seems like a more obvious option since we have access to all the props of `ColumnLayer`. Will update the code.
