### PR TITLE
Fix Picking Module object highlighting

### LINKED ISSUE #1229: Picking: highlighting with selectedObjectIndex is broken

### PR DESCRIPTION
**Pull request by 1chandu**
- Object highlighting uniforms should be set during drawing mode.
- Rename `getPickingModuleParameters` -> `getObjectHighlightParameters`

Fixes #1229 

Verified with layer-browser (`picking`, `selectedObjectIndex` and `autoHighlight`)

### CODE REVIEW

File: src/core/lib/draw-layers.js [hunk 1]
```diff
@@ -238,11 +238,12 @@ function drawLayerInViewport({gl, layer, layerIndex, drawPickingColors, glViewpo
 
   if (drawPickingColors) {
     // TODO - Disable during picking
```
Comment (georgios-uber) [inline src/core/lib/draw-layers.js]: maybe remove todo?

File: src/core/lib/draw-layers.js [hunk 2]
```diff
@@ -238,11 +238,12 @@ function drawLayerInViewport({gl, layer, layerIndex, drawPickingColors, glViewpo
...
-    Object.assign(moduleParameters, getPickingModuleParameters(layer));
 
     Object.assign(layerParameters, {
       blendColor: [0, 0, 0, (layerIndex + 1) / 255]
     });
+  } else {
+    Object.assign(moduleParameters, getObjectHighlightParameters(layer));
   }
 
   withParameters(gl, layerParameters, () => {
```
Comment (Pessimistress) [inline src/core/lib/draw-layers.js]: `layer.drawLayer` already calls `withParameters(this.context.gl, parameters, ...)`. Is it necessary to nest another level here?

Comment (1chandu) [reply src/core/lib/draw-layers.js]: Good find, fixed.
